spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://178.128.207.116:3306/TENNISCLUB
    #url: jdbc:mysql://localhost:3306/TENNISCLUB
    #username: apigw
    #password: Apigw123+
    username: tunahancakil
    password: 123456Tt+
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 10
      minimumIdle: 5
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/test/changelog-master.yml

server:
  port: 8091

jwt:
  secret: javainuse