spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://178.128.207.116:3306/TENNISCLUB
    username: root
    password: 123456Tt+
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/test/changelog-master.yml

server:
  port: 8091